CREATE TABLE IF NOT EXISTS dkgallery.owners (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    image_id INT,
    user_id INT,
    FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE);